<?php 

$remaining = array(
    'routing' => 'fix the issues with the routes for the Entities controller',
    'forms' => 'figure out a nice, clean way to deal with the data going to and coming from those restful update urls',
    'menu' => 'figure out a way to make the menu dynamically generated by the views defined in app/views'
);

?>

<h2>mTracker project To Do</h2>
<dl>
<?php foreach( $remaining as $key => $value):?>
	<dt><?=$key;?></dt>
	<dd><?=$value;?></dd>
<?php endforeach;?>
</dl>
